name: CI

on:
  schedule:
    # 00:00 on Wednesday
    - cron: '0 0 * * 3'
  push:
    branches:
      - devel

jobs:
  build-check-on-ros1:
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [noetic]
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.rosdistro }}-ros-base
    defaults:
      run:
        shell: bash
    steps:
      # System update
      - name: Run apt-upgrade
        run: |
          sudo apt update
          sudo apt --yes upgrade
          sudo apt install -y git
      # Checkout core
      - name: Checkout layered_hardware
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/layered_hardware
          path: src/layered_hardware
      # Checkout extensions
      - name: Checkout layered_hardware_extensions
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/layered_hardware_extensions
          path: src/layered_hardware_extensions
      # Checkout dynamixel
      - name: Checkout layered_hardware_dynamixel
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/layered_hardware_dynamixel
          path: src/layered_hardware_dynamixel
      # Checkout epos
      - name: Checkout layered_hardware_epos
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/layered_hardware_epos
          path: src/layered_hardware_epos
      # Checkout unitree
      - name: Checkout layered_hardware_unitree
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/layered_hardware_unitree
          path: src/layered_hardware_unitree
          submodules: true
      # Checkout gazebo
      - name: Checkout layered_hardware_gazebo
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/layered_hardware_gazebo
          path: src/layered_hardware_gazebo
      # Checkout misc
      - name: Checkout ros_controll_extensions
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/ros_control_extensions
          path: src/ros_control_extensions
      - name: Checkout ros_controllers_extensions
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/ros_controllers_extensions
          path: src/ros_controllers_extensions
      # Install dependencies
      - name: Run rosdep-install
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          sudo apt update
          rosdep update --rosdistro ${{ matrix.rosdistro }}
          sudo rosdep install --default-yes -r --ignore-src --from-paths src --rosdistro ${{ matrix.rosdistro }}
      # catkin_make
      - name: Build
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          catkin_make
      # run_tests
      - name: Run tests
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          catkin_make run_tests

  build-check-on-ros2:
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [humble, jazzy]
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.rosdistro }}-ros-base
    defaults:
      run:
        shell: bash
    steps:
      # System update
      - name: Run apt-upgrade
        run: |
          sudo apt update
          sudo apt --yes upgrade
      # Checkout core
      - name: Checkout layered_hardware
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/layered_hardware
          ref: ${{ matrix.rosdistro }}
          path: src/layered_hardware
      # Checkout dynamixel
      - name: Checkout layered_hardware_dynamixel
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/layered_hardware_dynamixel
          ref: ${{ matrix.rosdistro }}
          path: src/layered_hardware_dynamixel
      # Checkout epos
      - name: Checkout layered_hardware_epos
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/layered_hardware_epos
          ref: ${{ matrix.rosdistro }}
          path: src/layered_hardware_epos
      # Checkout unitree
      - name: Checkout layered_hardware_unitree
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/layered_hardware_unitree
          ref: ${{ matrix.rosdistro }}
          path: src/layered_hardware_unitree
          submodules: true
      # Checkout ignition
      - name: Checkout layered_hardware_ign
        if: ${{ matrix.rosdistro == 'humble' }}
        uses: actions/checkout@v4
        with:
          repository: yoshito-n-students/layered_hardware_ign
          ref: ${{ matrix.rosdistro }}
          path: src/layered_hardware_ign
      # Install dependencies
      - name: Run rosdep-install
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          sudo apt update
          rosdep update --rosdistro ${{ matrix.rosdistro }}
          sudo rosdep install --default-yes -r --ignore-src --from-paths src --rosdistro ${{ matrix.rosdistro }}
      # colcon build
      - name: Build
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          colcon build --event-handlers console_cohesion+
      # colcon test
      - name: Test
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          colcon test --event-handlers console_cohesion+