name: CI
on:
  push:
    branches:
      - devel
jobs:
  ci:
    strategy:
      matrix:
        include:
          - rosdistro: kinetic
            dart-cmd: |
              sudo apt update
              sudo apt --yes install software-properties-common
              sudo apt-add-repository ppa:dartsim/ppa
              sudo apt update
              sudo apt --yes install libdart6-all-dev
          - rosdistro: melodic
            dart-cmd: |
              sudo apt update
              sudo apt --yes install software-properties-common
              sudo apt-add-repository ppa:dartsim/ppa
              sudo apt update
              sudo apt --yes install libdart6-all-dev
          - rosdistro: noetic
            dart-cmd: |
              sudo apt update
              sudo apt --yes install libdart-all-dev
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.rosdistro }}-ros-base
    defaults:
      run:
        shell: bash
    steps:
      # Checkout core
      - name: Checkout layered_hardware
        uses: actions/checkout@v2
        with:
          repository: yoshito-n-students/layered_hardware
          path: src/layered_hardware
      # Checkout dynamixel
      - name: Checkout layered_hardware_dynamixel
        uses: actions/checkout@v2
        with:
          repository: yoshito-n-students/layered_hardware_dynamixel
          path: src/layered_hardware_dynamixel
      # Checkout epos
      - name: Checkout layered_hardware_epos
        uses: actions/checkout@v2
        with:
          repository: yoshito-n-students/layered_hardware_epos
          path: src/layered_hardware_epos
      # Checkout gazebo
      - name: Checkout layered_hardware_gazebo
        uses: actions/checkout@v2
        with:
          repository: yoshito-n-students/layered_hardware_gazebo
          path: src/layered_hardware_gazebo
      # Checkout misc
      - name: Checkout ros_controll_extensions
        uses: actions/checkout@v2
        with:
          repository: yoshito-n-students/ros_control_extensions
          path: src/ros_control_extensions
      - name: Checkout ros_controllers_extensions
        uses: actions/checkout@v2
        with:
          repository: yoshito-n-students/ros_controllers_extensions
          path: src/ros_controllers_extensions
      # Rosdep-install
      - name: Install dependencies
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          ${{ matrix.dart-cmd }}
          sudo apt update
          rosdep update
          sudo rosdep --default-yes -r --ignore-src --from-paths src --rosdistro ${{ matrix.rosdistro }} install
      # catkin_make
      - name: Build
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          catkin_make
      # run_tests
      - name: Run tests
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          catkin_make run_tests